on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: [1.7.4]
    name: Test with Deno ${{ matrix.deno }}

    steps:
      - uses: actions/checkout@master

      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}

      - name: Check format
        run: deno fmt --check **/*.ts

      - name: Run tests
        run: deno test
